//! Enumerate the conformance vectors that ship in this crate, at build time.
//!
//! # Why a build script rather than a list of `include_str!`s
//!
//! The packaged firewall must check **every vector the consumer actually received**,
//! not a set named in source. Python and TypeScript get that by reading their
//! package's `vectors/` directory at runtime. An installed Rust binary cannot: after
//! `cargo install` the crate tarball is gone and there is no directory left to read,
//! so the bytes have to be embedded at compile time — and `include_str!` takes a
//! literal path, which is exactly the fixed set that let `chain_v1` and
//! `attestation_v1` ship unchecked in 0.4.0.
//!
//! Build time is the correct analogue. `cargo install` compiles from the tarball the
//! consumer fetched, so scanning `tests/vectors/` here enumerates precisely what
//! shipped in *that* artifact. Adding a vector to the crate adds it to this table
//! with no source change, and the binary then fails closed if nothing checks it.
//!
//! # This never fails the build
//!
//! A missing or unreadable `tests/vectors/` emits an EMPTY table rather than
//! panicking. The firewall is a binary target, but this script runs for every
//! consumer who merely depends on the library, and breaking an unrelated build over
//! absent test data would be a worse failure than the one being guarded against.
//!
//! Failing closed still happens, in the right place: an empty table makes
//! `vaid-mint-conformance` exit BLOCKER at runtime, because a firewall that checked
//! nothing must never report PASS.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let vectors_dir = manifest_dir.join("tests/vectors");

    // Re-run when a vector is added, removed or edited. Without this a stale table
    // would survive an incremental build — a firewall silently checking yesterday's
    // set is the same defect this file exists to prevent.
    println!("cargo:rerun-if-changed={}", vectors_dir.display());

    let mut vectors: BTreeMap<String, PathBuf> = BTreeMap::new();
    if let Ok(entries) = fs::read_dir(&vectors_dir) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().into_owned();
            if name.ends_with(".json") {
                println!("cargo:rerun-if-changed={}", entry.path().display());
                vectors.insert(name, entry.path());
            }
        }
    }

    let mut generated = String::from(
        "// @generated by build.rs — do not edit.\n\
         //\n\
         // Every `.json` under `tests/vectors/` at build time, embedded by value.\n\
         // Empty means the crate shipped without its vectors; the firewall treats\n\
         // that as a BLOCKER rather than as nothing to check.\n\
         pub static EMBEDDED_VECTORS: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &vectors {
        generated.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            name,
            path.display().to_string()
        ));
    }
    generated.push_str("];\n");

    let out = Path::new(&env::var("OUT_DIR").expect("cargo sets this")).join("embedded_vectors.rs");
    fs::write(&out, generated).expect("OUT_DIR is writable");
}
